# Generated by Django 4.0.3 on 2022-03-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='bodytype',
        ),
        migrations.AddField(
            model_name='cars',
            name='bodytype',
            field=models.ForeignKey(help_text='Select body type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bodytype'),
        ),
        migrations.RemoveField(
            model_name='cars',
            name='carsclass',
        ),
        migrations.AddField(
            model_name='cars',
            name='carsclass',
            field=models.ForeignKey(help_text='Choose a class for this car', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.carsclass'),
        ),
    ]
