# Generated by Django 4.0.3 on 2022-03-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_cars_bodytype_cars_bodytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(help_text='Enter the type of transmission', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.ManyToManyField(help_text='the type of transmission', to='catalog.transmission'),
        ),
    ]
