# Generated by Django 4.0.3 on 2022-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_carinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
