# Generated by Django 4.0.3 on 2022-04-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_orders_cars_price_carinstance_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinstance',
            name='orders',
        ),
        migrations.AddField(
            model_name='orders',
            name='car_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.carinstance'),
        ),
    ]
