# Generated by Django 4.0.3 on 2022-04-09 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_carinstance_orders_orders_car_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinstance',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='comments',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='place_finish',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='place_start',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this  order across whole catalog Rent Car', primary_key=True, serialize=False),
        ),
    ]
