# Generated by Django 4.0.3 on 2022-04-09 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0010_remove_carinstance_status_orders_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='date_finish',
        ),
        migrations.RemoveField(
            model_name='carinstance',
            name='date_start',
        ),
        migrations.AddField(
            model_name='orders',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
